# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP

#----------------------------------------------------
# Add databases, templates, substitutions like this

DB += ip330Scan.template
DB += ip330Scan.substitutions
DB += ip330PID.db

include $(TOP)/config/RULES.Db
#----------------------------------------
#  ADD RULES AFTER THIS LINE

