# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP

#----------------------------------------------------
# Add databases, templates, substitutions like this


include $(TOP)/config/RULES.Db
#----------------------------------------
#  ADD RULES AFTER THIS LINE

