# Makefile.Vx
TOP = ../../..
include $(TOP)/config/CONFIG_APP

SRCS.cc += ../quadEM.cc
QUADEMLIBOBJS += quadEM.o
SRCS.cc += ../quadEMScan.cc
QUADEMLIBOBJS += quadEMScan.o
SRCS.cc += ../quadEMSweep.cc
QUADEMLIBOBJS += quadEMSweep.o
SRCS.cc += ../quadEMPID.cc
QUADEMLIBOBJS += quadEMPID.o
SRCS.cc += ../devQuadEM.cc
LIBOBJS += devQuadEM.o
LIBNAME = devQuadEMLib
quadEMLib: $(QUADEMLIBOBJS)
	$(LINK.c) $@ $(QUADEMLIBOBJS)
PROD += quadEMLib

include $(TOP)/config/RULES.Vx

